= API Gateway - Content Caching
:toc: manual

== OSData App

=== Run Local

[source, bash]
.*Start*
----
docker run -it --rm --name osdata -p 8090:8090 cloudadc/osdata:1.0.1 
----

[source, bash]
.*Test*
----
http://127.0.0.1:8090
for i in {1..10} ; do curl http://127.0.0.1:8090/images/$i.png -I ; done
for i in {1..3} ; do curl http://127.0.0.1:8090/docs/$i.docx -I ; done
for i in {1..3} ; do curl http://127.0.0.1:8090/docs/$i.pptx -I ; done
for i in {1..3} ; do curl http://127.0.0.1:8090/docs/$i.pdf -I ; done
for i in {1..4} ; do curl http://127.0.0.1:8090/vedio/$i.mp4 -I ; done
for i in {1..10} ; do curl http://127.0.0.1:8090/html/$i.html -I ; done
----

=== Access OSData App Via NGINX

*NGINX Configuration*

* link:cache/catch.conf[catch.conf]
* link:cache/batch.sh[batch.sh]

[source, bash]
.*Run Batch Test*
----
./cache/batch.sh 10.1.20.204 7001
----

== Specifying Which Requests to Cache

=== proxy_cache_min_uses

[source, bash]
.*1. Continute access http request 5 times*
----
$ for i in {1..6} ; do curl -s http://10.1.20.204:7001/html/1.html -I | grep X-Proxy-Cache; done
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: HIT
----

[source, bash]
.*2. View the cached content*
----
/data/nginx/cache/
|-- 0
|   `-- 2f
|	`-- 589db6285db9d2b221991093581102f0
----

=== proxy_cache_methods

[source, bash]
.*1. Continute access http request 5 times*
----
for i in {1..5} ; do curl http://10.1.20.204:7001/html/user.html -X PUT ; done 
----

*2. View the cached content*

There is no content cached.

== Limiting or Disabling Caching

=== proxy_cache_valid

[source, bash]
.*1. Configuration*
----
proxy_cache_valid 200 304 2m;
proxy_cache_valid any 1m;
----

[source, bash]
.*2. Test return 200*
----
$ for i in {1..6} ; do curl -s http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache ; done
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: HIT
----

=== proxy_cache_bypass

[source, bash]
.*Configuration*
----
proxy_cache_bypass $cookie_nocache $cookie_comment $arg_nocache $arg_comment $http_cachepurge;
----

[source, bash]
.*1. Test Cookie nocache*
----
$ curl -s http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: HIT

$ curl -s --cookie "nocache=1" http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: BYPASS

$ curl -s --cookie "nocache=0" http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: HIT

$ curl -s --cookie "nocache=any" http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: BYPASS
----

[source, bash]
.*2. Test nocache parameter*
----
$ curl -s http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: HIT

$ curl -s http://10.1.20.204:7001/html/10.html?nocache=1 -I | grep X-Proxy-Cache
X-Proxy-Cache: BYPASS

$ curl -s http://10.1.20.204:7001/html/10.html?nocache=0 -I | grep X-Proxy-Cache
X-Proxy-Cache: MISS

$ curl -s http://10.1.20.204:7001/html/10.html?nocache=any -I | grep X-Proxy-Cache
X-Proxy-Cache: BYPASS
----

[source, bash]
.*3. Test HTTP Header*
----
$ curl -s http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: HIT

$ curl -s -H "cachepurge: 1" http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: BYPASS

$ curl -s -H "cachepurge: 0" http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: HIT

$ curl -s -H "cachepurge: any" http://10.1.20.204:7001/html/10.html -I | grep X-Proxy-Cache
X-Proxy-Cache: BYPASS
----

=== proxy_no_cache

[source, bash]
.*Configuration*
----
proxy_no_cache $cookie_notcache $arg_notcache $http_authorization;
----

NOTE: `proxy_no_cache` is used to specify which requests should not be cached by Nginx. If a request matches the conditions specified in proxy_no_cache, Nginx will not cache the response, even if caching is enabled for the corresponding location.

[source, bash]
.*1. Test cookie notcache*
----
$ for i in {1..6} ; do curl -s --cookie "notcache=1" http://10.1.20.204:7001/html/1.html -I | grep X-Proxy-Cache ; done
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS

$ for i in {1..6} ; do curl -s --cookie "notcache=any" http://10.1.20.204:7001/html/1.html -I | grep X-Proxy-Cache ; done
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
----

[source, bash]
.*2. Test Parameter notcache*
----
$ for i in {1..6} ; do curl -s http://10.1.20.204:7001/html/1.html?notcache=1 -I | grep X-Proxy-Cache ; done
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS

$ for i in {1..6} ; do curl -s http://10.1.20.204:7001/html/1.html?notcache=any -I | grep X-Proxy-Cache ; done
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
----

[source, bash]
.*3. Test Http Request Variable*
----
$ for i in {1..6} ; do curl -s -H "authorization: YWRtaW46YWRtaW4K" http://10.1.20.204:7001/html/1.html -I | grep X-Proxy-Cache ; done
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
X-Proxy-Cache: MISS
----

== Purging Content From The Cache

[source, bash]
.*1. Trigger the Content Cache*
----
for j in {1..5} ; do for i in {1..6} ; do curl -s http://10.1.20.204:7001/html/$j.html ; done ; done
----

[source, bash]
.*2. Check the Cache Content*
----
/data/nginx/cache/
|-- 0
|   `-- 2f
|       `-- 589db6285db9d2b221991093581102f0
|-- 1
|   `-- 16
|       `-- 2ad064b44bc1d4e173875927df5ea161
|-- 2
|   `-- 64
|       `-- b80c469e3cfd6c68f675a01e0799d642
|-- b
|   `-- ed
|       `-- 33a66204dce6ea778cff6e9c07bededb
`-- c
    `-- 71
        `-- 7fe06fcb24ad18e1b804c50362b1071c

10 directories, 5 files
----

[source, bash]
.*3. Purging One*
----
$ curl -X PURGE http://10.1.20.204:7001/html/4.html -I
HTTP/1.1 204 No Content
Server: nginx/1.23.2
Date: Mon, 10 Apr 2023 10:17:23 GMT
Connection: keep-alive
----

[source, bash]
.*4. Check the Cache Content*
----
/data/nginx/cache/
|-- 0
|   `-- 2f
|       `-- 589db6285db9d2b221991093581102f0
|-- 1
|   `-- 16
|       `-- 2ad064b44bc1d4e173875927df5ea161
|-- 2
|   `-- 64
|-- b
|   `-- ed
|       `-- 33a66204dce6ea778cff6e9c07bededb
`-- c
    `-- 71
        `-- 7fe06fcb24ad18e1b804c50362b1071c

10 directories, 4 files
----

[source, bash]
.*5. Purging All*
----
$ curl -X PURGE http://10.1.20.204:7001/* -I
HTTP/1.1 204 No Content
Server: nginx/1.23.2
Date: Mon, 10 Apr 2023 10:19:55 GMT
Connection: keep-alive
----

[source, bash]
.*6. Check the Cache Content*
----
/data/nginx/cache/
|-- 0
|   `-- 2f
|-- 1
|   `-- 16
|-- 2
|   `-- 64
|-- b
|   `-- ed
`-- c
    `-- 71

10 directories, 0 files
----

== Byte-Range Caching

=== Basic Byte-Range Caching Configuration

[source, bash]
.*1. Configuration*
----
    location /vedio {
        slice             2m;
        proxy_cache       objectstoragecache;
        proxy_cache_key   $scheme$proxy_host$request_uri$slice_range;
        proxy_cache_min_uses 3;
        proxy_set_header  Range $slice_range;
        proxy_cache_valid 200 206 1h;
        proxy_cache_valid any 1m;
        add_header X-Proxy-Cache $upstream_cache_status;
        proxy_pass http://images.gateway.io:8090;
    }
----

[source, bash]
.*2. Check the Cache Content*
----
/data/nginx/cache/

0 directories, 0 files
----

[source, bash]
.*3. Access the Vedio File*
----
curl  -s http://10.1.20.204:7001/vedio/1.mp4 -o 1.mp4
----

[source, bash]
.*4. Check the Cache Content*
----
/data/nginx/cache/
|-- 5
|   `-- c1
|	`-- 3da38738db3c55ed7740346a56027c15
|-- 7
|   `-- 56
|	`-- 07a5b06f5fdfabc3a72415f90f35a567
|-- 9
|   `-- 52
|	`-- d5f97a53843566f3b1a5775aa2c29529
|-- a
|   `-- ad
|	`-- 66e1be52dc636e8508580dfcb3a87ada
|-- d
|   `-- d4
|	`-- 91c3fbad018c4f4d7e45408b67ca5d4d
`-- e
    `-- af
	`-- 0d05ec5233c55f1aba16260cdb9edafe

12 directories, 6 files
----

=== Performance Comparision

[source, bash]
.*1. Execute Performance Comparision Request*
----
$ for i in {1..6}; do curl -w "@cache/curl-format.txt" -o /dev/null -s http://10.1.20.204:7001/vedio/1.mp4 ;echo; done
     time_namelookup:  0.005493s
        time_connect:  0.005932s
     time_appconnect:  0.000000s
    time_pretransfer:  0.005986s
       time_redirect:  0.000000s
  time_starttransfer:  0.008753s
                     ----------
          time_total:  0.461682s

     time_namelookup:  0.000360s
        time_connect:  0.002648s
     time_appconnect:  0.000000s
    time_pretransfer:  0.002684s
       time_redirect:  0.000000s
  time_starttransfer:  0.005103s
                     ----------
          time_total:  0.443665s

     time_namelookup:  0.000400s
        time_connect:  0.002707s
     time_appconnect:  0.000000s
    time_pretransfer:  0.002744s
       time_redirect:  0.000000s
  time_starttransfer:  0.004909s
                     ----------
          time_total:  0.367407s

     time_namelookup:  0.000352s
        time_connect:  0.000734s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000766s
       time_redirect:  0.000000s
  time_starttransfer:  0.001100s
                     ----------
          time_total:  0.175896s

     time_namelookup:  0.000422s
        time_connect:  0.001986s
     time_appconnect:  0.000000s
    time_pretransfer:  0.002015s
       time_redirect:  0.000000s
  time_starttransfer:  0.002301s
                     ----------
          time_total:  0.171978s

     time_namelookup:  0.000411s
        time_connect:  0.002200s
     time_appconnect:  0.000000s
    time_pretransfer:  0.002232s
       time_redirect:  0.000000s
  time_starttransfer:  0.002511s
                     ----------
          time_total:  0.109206s
----

* link:cache/curl-format.tx[curl-format.tx]
* Total 6 request mp4 file 6 times, the first 3 times mp4 not cached on NGINX, the second 3 times mp4 cached on NGINX.

*2. How silce size affect total time*

|===
|Time(s) |no-cache |slice(1m) |slice(5m) |slice(10m)

|time_connect
|0.001744
|0.000615
|0.002200
|0.000690

|time_pretransfer
|0.001789
|0.000684
|0.002232
|0.000722

|time_starttransfer
|0.004375
|0.000990
|0.002511
|0.002443

|time_total
|0.496134
|0.201303
|0.109206
|0.182252
|===

NOTE: HIT Cache can increase performance, the slice size can affect the total time spend.

[source, bash]
.**
----

----

