= API Gateway
:toc: manual

== server

=== listen 指令分别监听端口、IP、及IP:端口的差异

[source, bash]
.*1. NGINX Configuration*
----
server {
    listen    9001;
}

server {
    listen    10.1.10.195:9001;
}

server {
    listen    10.1.10.195;
}
----

* link:gw-server.d/listen.conf[listen.conf]

[source, bash]
.*2. NGINX Listen list*
----
# netstat -antulop | grep nginx
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      1719/nginx: master   off (0.00/0/0)
tcp        0      0 10.1.10.195:80          0.0.0.0:*               LISTEN      1719/nginx: master   off (0.00/0/0)
----

[source, bash]
.*3. Test*
----
~]# curl http://example.com:9001
10.1.10.195:9001

~]# curl http://10.1.10.195:9001 
10.1.10.195:9001
----

*4. Conclusion*

|===
|Configuration |Listen

|listen 9001
|0.0.0.0:9001

|listen 10.1.10.195:9001
|10.1.10.195:9001

|listen 10.1.10.195
|10.1.10.195:80
|===

* If both `listen 9001` and `listen 10.1.10.195:9001` exist, the NGINX listen on `0.0.0.0:9001`.
* IP has high priority than PORT

=== defaut_server

[source, bash]
.*1. Configuration*
----
server {
    listen 9002;
    server_name "bar.com";
}

server {
    listen 9002;
    server_name "foo.com";
}

server {
    listen 9003;
    server_name "bar.com";
}

server {
    listen 9003 default_server;
    server_name "foo.com";
}
----

* link:gw-server.d/defaut_server.conf[defaut_server.conf]

[source, bash]
.*2. Test*
----
~]# curl http://example.com:9002 
from 9002 bar.com

~]# curl http://example.com:9003 
from 9003 foo.com
----

*3. Conclusion*

* The `default_server` are used only can be used while `listen` and `server_name` can not route HTTP request.
* If `listen` and `server_name` can not route HTTP request, and no `default_server`, the first server block will be used.

=== Host Name Based Route

[source, bash]
.*1. Configuration*
----
server {
    listen    9004;
    server_name "foo.example.com";
}

server {
    listen    9004;
    server_name "bar.example.com";
}

server {
    listen    9004;
    server_name "zoo.example.com";
}
----

* link:gw-server.d/server_name.conf[server_name.conf]

[source, bash]
.*2. Test*
----
~]# curl  -H "Host: foo.example.com" http://10.1.10.195:9004 
from foo.example.com

~]# curl  -H "Host: bar.example.com" http://10.1.10.195:9004 
from bar.example.com

~]# curl  -H "Host: zoo.example.com" http://10.1.10.195:9004 
from zoo.example.com
----

*3. Conclusion*

* The `server_name` match HTTP Request Header `Host`, which can be used as Host Based Route.

=== Host Name Based Route(catch-all, multi)

[source, bash]
.*1. Configuration*
----
server {
    listen    9005;
    server_name _;
}

server {
    listen    9005;
    server_name  a.example.com  b.example.com  c.example.com  *.example.com;
}
----

* link:gw-server.d/server_name_empty.conf[server_name_empty.conf]

[source, bash]
.*2. Test*
----
~]# for i in a b c d ; do curl  -H "Host: $i.example.com" http://10.1.10.195:9005 ; echo ; done
from multi, a.example.com
from multi, b.example.com
from multi, c.example.com
from multi, d.example.com

~]# for i in a b c d ; do curl  -H "Host: $i.example.org" http://10.1.10.195:9005 ; echo ; done
from catch-all, a.example.org
from catch-all, b.example.org
from catch-all, c.example.org
from catch-all, d.example.org
----

*3. Conclusion*

* The `server_name` can match multiple host, the "_" catch all.

=== Host Name Based Route(wildcard, regular expressions)

[source, bash]
.*1. Configuration*
----
server {
    listen    9006;
    server_name *.example.com;
}

server {
    listen    9006;
    server_name test.*;
}

server {
    listen    9006;
    server_name  ~^(?<user>.+)\.example\.net$;
}
----

* link:gw-server.d/server_name_regular.conf[server_name_regular.conf]

[source, bash]
.*2. Test*
----
~]# curl  -H "Host: test.com" http://10.1.10.195:9006 
from test.*, test.com

~]# curl  -H "Host: test.example.com" http://10.1.10.195:9006 
from *.example.com, test.example.com

~]# curl  -H "Host: test.example.net" http://10.1.10.195:9006 
from test.*, test.example.net

~]# curl  -H "Host: user1.example.net" http://10.1.10.195:9006
from regular expressions names, user1.example.net
----

*3. Conclusion*

* starting with wildcard has high priority than ending with
* wildcard has high priority than regular expression

=== HTTPS 服务的监听

[source, bash]
.*1. Configurtion*
----
server {
    listen              9007 ssl;
    server_name         example.com;
    ssl_certificate     gw-server.d/crt/example.com.crt;
    ssl_certificate_key gw-server.d/crt/example.com.key;
    ssl_password_file   gw-server.d/crt/example.com.pass;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
}
----

* link:gw-server.d/listen-ssl.conf[listen-ssl.conf]
* link:gw-server.d/crt/example.com.crt[example.com.crt]
* link:gw-server.d/crt/example.com.key[example.com.key]
* link:gw-server.d/crt/example.com.pass[example.com.pass]

[source, bash]
.*2. Test*
----
~]# curl --cacert example.com.crt https://example.com:9007 
from 9007 ssl
----

*3. Conclusion*

* NGINX can be used SSL offload.

=== IPv6 服务监听

[source, bash]
.*1. Configuration*
----
server {
    listen    [fd15:4ba5:5a2b:1003:9d08:1036:986e:b1f9]:9008 ipv6only=on;
    server_name example.com;
}

server {
    listen    9009;
    listen    [::]:9009;
    server_name example.com;
}
----

* link:gw-server.d/listen-ipv6.conf[listen-ipv6.conf]

[source, bash]
.*2. Test*
----
~]# curl -g -6 http://[fd15:4ba5:5a2b:1003:9d08:1036:986e:b1f9]:9008
from [fd15:4ba5:5a2b:1003:9d08:1036:986e:b1f9]:9008

~]# curl -g -6 http://[fd15:4ba5:5a2b:1003:9d08:1036:986e:b1f9]:9009
from [fd15:4ba5:5a2b:1003:9d08:1036:986e:b1f9]:9009

~]# curl http://10.1.10.195:9009
from 10.1.10.195:9009
----

*3. Conclusion*

* Nginx can listen on specific nic ipv6 address
* Nginx can listen on dual-stack(IPv4, Ipv6) on all L3 IP address from all L2 nics.

=== gRPC 服务监听

[source, bash]
.*1. Configurtaion*
----
server {
  listen 9041 http2;
}
----

* link:gw-type.d/grpc.conf[gw-type.d/grpc.conf]

[source, bash]
.*2. Test*
----
~]# echo "ADDRESS=10.1.10.195:9041" > address
~]# docker run --env-file ./address cloudadc/grpc-go-greeting:0.1 greeter_client "NGINX"
2023/03/31 02:52:18 Greeting: Hello NGINX
----

=== TCP 服务监听

[source, bash]
.*1. Backend*
----
ttcp -r
ttcp -r
----

[source, bash]
.*2. Configurtaion*
----
server {
  listen 9042;
}
----

* link:gw-type.d/stream/tcp.conf[gw-type.d/stream/tcp.conf]

[source, bash]
.*3. Test*
----
ttcp -t -p 9042 10.1.10.195
----

=== UDP 服务监听

[source, bash]
.*1. Backend*
----
ttcp -r -u
ttcp -r -u
----

[source, bash]
.*2. Configurtaion*
----
server {
  listen 9042 udp;
}
----

* link:gw-type.d/stream/udp.conf[gw-type.d/stream/udp.conf]

[source, bash]
.*3. Test*
----
ttcp -t -u -p 9042 10.1.10.195
----

== location

=== Regular Expression Syntax

[source, bash]
----
        =     -    The URI must match the specified pattern exactly.
        ^~    -    The URI must begin with the specified pattern.
        None  -    The URI must begin with the specified pattern.
        ~     -    The URI must be a case-sensitive match to the specified regular expression.
        ~*    -    The URI must be a case-insensitive match to the specified regular expression.
        @     -    Defines a named location block.

        ()    -    Match group or evaluate the content of ().
        []    -    Match any char inside [].
        {}    -    Match a specific number of occurrence. eg, [0-9]{3} match 342 but not 32, {2,4} match length of 2, 3 and 4.

        |     -    Or.
        ?     -    Check for zero or one occurrence of the previous char, eg jpe?g.
        .     -    Any char.
        *     -    Match zero, one or more occurrence of the previous char.
        .*    -    Match zero, one or more occurrence of any char.
        +     -    Match one or more occurrence of the previous char.
        !     -    Not (negative look ahead).

        \     -    Escape the next char.
        /     -    The forward slash / is used to match any sub location, including none example location /.

        ^     -    Match the beginning of the text (opposite of $). By itself, ^ is a shortcut for all paths (since they all have a beginning).
        $     -    The expression must be at the end of the evaluated text(no char/text after the match), $ is usually used at the end of a regex location expression.
----

[source, bash]
.**
----

----

== Service Type

=== HTTP

[source, bash]
.*1. Configuration*
----
upstream backendHTTP {
  zone upstream_backendHTTP 64k;
  server 10.1.20.203:8080;
  server 10.1.20.204:8080;
}

server {
  listen 9040;
  status_zone server_backendHTTP;
  location / {
    status_zone location_backendHTTP;
    proxy_pass http://backendHTTP;
  }
}
----

* link:gw-type.d/http.conf[gw-type.d/http.conf]

[source, bash]
.*2. Test*
----
$ curl http://10.1.10.195:9040/test -I
HTTP/1.1 200 OK
Server: nginx/1.23.2
Date: Fri, 31 Mar 2023 02:36:27 GMT
Content-Type: text/plain
Content-Length: 147
Connection: keep-alive
Expires: Fri, 31 Mar 2023 02:36:26 GMT
Cache-Control: no-cache
----

=== gRPC

[source, bash]
.*1. Configurtaion*
----
upstream backendgRPC {
  zone upstream_backendgRPC 64k;
  server 10.1.20.203:8009;
  server 10.1.20.204:8009;
}

server {
  listen 9041 http2;
  status_zone server_backendgRPC;
  location / {
    status_zone location_backendgRPC;
    grpc_pass grpc://backendgRPC;
  }
}
----

* link:gw-type.d/grpc.conf[gw-type.d/grpc.conf]

[source, bash]
.*2. Test*
----
~]# echo "ADDRESS=10.1.10.195:9041" > address
~]# docker run --env-file ./address cloudadc/grpc-go-greeting:0.1 greeter_client "NGINX"
2023/03/31 02:52:18 Greeting: Hello NGINX
----

=== TCP

[source, bash]
.*1. Backend*
----
ttcp -r
ttcp -r
----

[source, bash]
.*2. Configurtaion*
----
upstream backendTCP {
  zone upstream_backendTCP 64k;
  server 10.1.20.203:5001;
  server 10.1.20.204:5001;
}

server {
  listen 9042;
  status_zone server_backendTCP;
  proxy_pass  backendTCP;
}
----

* link:gw-type.d/stream/tcp.conf[gw-type.d/stream/tcp.conf]

[source, bash]
.*3. Test*
----
ttcp -t -p 9042 10.1.10.195
----

=== UDP

[source, bash]
.*1. Backend*
----
ttcp -r -u
ttcp -r -u
----

[source, bash]
.*2. Configurtaion*
----
upstream backendUDP {
  zone upstream_backendUDP 64k;
  server 10.1.20.203:5001;
  server 10.1.20.204:5001;
}

server {
  listen 9042 udp;
  status_zone server_backendUDP;
  proxy_pass  backendUDP;
}
----

* link:gw-type.d/stream/udp.conf[gw-type.d/stream/udp.conf]

[source, bash]
.*3. Test*
----
ttcp -t -u -p 9042 10.1.10.195
----

== Health Check

=== HTTP 被动健康检查

[source, bash]
.*1. Configuration*
----
upstream backendHTTP1 {
  zone upstream_backendHTTP1 64k;
  server 10.1.20.203:8080 max_fails=3 fail_timeout=3s;
  server 10.1.20.204:8080 max_fails=3 fail_timeout=3s;
}
----

* link:gw-health.d/http1.conf[gw-health.d/http1.conf]

[source, bash]
.*2. Test*
----
for i in {1..10} ; do curl http://10.1.10.195:9051/test ; done
----

=== HTTP 主动健康检查

[source, bash]
.*1. Configuration*
----
server {
  listen 9052;
  location / {
    health_check interval=10 passes=2 fails=3;
    proxy_pass http://backendHTTP2;
  }
}
----

* link:gw-health.d/http2.conf[gw-health.d/http2.conf]

[source, bash]
.*2. Test*
----
for i in {1..10} ; do curl http://10.1.10.195:9052/test ; done
----

[source, bash]
.*3. Verify*
----
$ curl -s http://10.1.10.195:8080/api/8/http/upstreams/backendHTTP2 -H 'accept: application/json' | jq '.peers[] | {server, state, health_checks}'
{
  "server": "10.1.20.203:8080",
  "state": "up",
  "health_checks": {
    "checks": 29,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
{
  "server": "10.1.20.204:8080",
  "state": "up",
  "health_checks": {
    "checks": 29,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
----

=== HTTP 主动健康检查(自定义返回内容)

[source, bash]
.*1. Configuration*
----
match server_ok {
    status 200-399;
    body ~ "health";
}

server {
  listen 9053;
  location / {
    health_check interval=10 passes=2 fails=3 uri=/health match=server_ok;
    proxy_pass http://backendHTTP3;
  }
}
----

link:gw-health.d/http3.conf[gw-health.d/http3.conf]

[source, bash]
.*2. Test*
----
for i in {1..10} ; do curl http://10.1.10.195:9053/test ; done
----

[source, bash]
.*3. Verify*
----
$ curl -s http://10.1.10.195:8080/api/8/http/upstreams/backendHTTP3 -H 'accept: application/json' | jq '.peers[] | {server, state, health_checks}'
{
  "server": "10.1.20.203:8080",
  "state": "up",
  "health_checks": {
    "checks": 49,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
{
  "server": "10.1.20.204:8080",
  "state": "up",
  "health_checks": {
    "checks": 49,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
----

=== gRPC 主动健康检查

[source, bash]
.*1. Configuration*
----
server {
  listen 9054 http2;
  location / {
    health_check type=grpc grpc_status=12;
    grpc_pass grpc://backendgRPC1;
  }
}
----

* link:gw-health.d/grpc.conf[gw-health.d/grpc.conf]

[source, bash]
.*2. Test*
----
$ curl -s http://10.1.10.195:8080/api/8/http/upstreams/backendgRPC1 -H 'accept: application/json' | jq '.peers[] | {server, state, health_checks}'
{
  "server": "10.1.20.203:8009",
  "state": "up",
  "health_checks": {
    "checks": 33,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
{
  "server": "10.1.20.204:8009",
  "state": "up",
  "health_checks": {
    "checks": 33,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
----

=== TCP 被动健康检查

[source, bash]
.*1. Configuration*
----
upstream backendTCP1 {
  zone upstream_backendTCP1 64k;
  server 10.1.20.203:8080 max_fails=2 fail_timeout=30s slow_start=30s;
  server 10.1.20.204:8080 max_fails=2 fail_timeout=30s slow_start=30s;
}
----

* link:gw-health.d/stream/tcp1.conf[gw-health.d/stream/tcp1.conf]

[source, bash]
.*2. Test*
----
for i in {1..10} ; do curl http://10.1.10.195:9055/test ; done
----

=== TCP 主动健康检查

[source, bash]
.*1. Configuration*
----
server {
  listen 9056;
  status_zone server_backendTCP2;
  proxy_pass  backendTCP2;
  health_check interval=10 passes=2 fails=3;
  health_check_timeout 5s;
}
----

* link:gw-health.d/stream/tcp2.conf[gw-health.d/stream/tcp2.conf]

[source, bash]
.*2. Test*
----
for i in {1..10} ; do curl http://10.1.10.195:9056/test ; done
----

[source, bash]
.*3. Verify*
----
$ curl -s http://10.1.10.195:8080/api/8/stream/upstreams/backendTCP2 -H 'accept: application/json' | jq '.peers[] | {server, state, health_checks}'
{
  "server": "10.1.20.203:8080",
  "state": "up",
  "health_checks": {
    "checks": 31,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
{
  "server": "10.1.20.204:8080",
  "state": "up",
  "health_checks": {
    "checks": 31,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
----

=== UDP 被动健康检查

[source, bash]
.*1. Configuration*
----
upstream backendUDP1 {
  zone upstream_backendUDP1 64k;
  server 10.1.20.203:5001 max_fails=2 fail_timeout=30s;
  server 10.1.20.204:5001 max_fails=2 fail_timeout=30s;
}
----

* link:gw-health.d/stream/udp1.conf[gw-health.d/stream/udp1.conf]

[source, bash]
.*2. Check*
----
$ curl -s http://10.1.10.195:8080/api/8/stream/upstreams/backendUDP1 -H 'accept: application/json' | jq '.peers[] | {server, state, health_checks}'
{
  "server": "10.1.20.203:5001",
  "state": "up",
  "health_checks": {
    "checks": 0,
    "fails": 0,
    "unhealthy": 0
  }
}
{
  "server": "10.1.20.204:5001",
  "state": "up",
  "health_checks": {
    "checks": 0,
    "fails": 0,
    "unhealthy": 0
  }
}

----

=== UDP 主动健康检查

[source, bash]
.*1. Configuration*
----
server {
  listen 9058 udp;
  status_zone server_backendUDP2;
  proxy_pass  backendUDP2;
  health_check interval=20 passes=2 fails=2 udp;
}
----

* link:gw-health.d/stream/udp2.conf[gw-health.d/stream/udp2.conf]

[source, bash]
.*2. Check*
----
$ curl -s http://10.1.10.195:8080/api/8/stream/upstreams/backendUDP2 -H 'accept: application/json' | jq '.peers[] | {server, state, health_checks}'
{
  "server": "10.1.20.203:5001",
  "state": "up",
  "health_checks": {
    "checks": 6,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
{
  "server": "10.1.20.204:5001",
  "state": "up",
  "health_checks": {
    "checks": 6,
    "fails": 0,
    "unhealthy": 0,
    "last_passed": true
  }
}
----

== Request Persistence

=== Source Address

[source, bash]
.*1. Configuration*
----
upstream backend_persist_source_addr {
    zone   backend_persist 64k;
    ip_hash;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
}
----

* link:gw-persist.d/source_addr.conf[source_addr.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9015/foo | grep name ; done
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8c30db968198
----

=== Sticky cookie

[source, bash]
.*1. Configuration*
----
upstream backend_persist_cookie {
    zone   backend_persist 64k;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
    sticky cookie srv_id expires=1h domain=.example.com path=/;
}
----

* link:gw-persist.d/cookie.conf[cookie.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s --cookie "srv_id=389841024adab882cf00e885942acaea; expires=Thu, 20-Apr-23 11:42:49 GMT; max-age=3600; domain=.example.com; path=/" http://10.1.10.195:9016/foo | grep name ; done
Server name: 8dbb74943174
Server name: 8dbb74943174
Server name: 8dbb74943174
Server name: 8dbb74943174
Server name: 8dbb74943174
----

== LB Algorithms

=== Round Robin 

[source, bash]
.*1. Configuration*
----
upstream backend_methods_rr {
    zone   backend_methods 64k;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
}
----

* link:gw-methods.d/rr.conf[rr.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9021/foo | grep name ; done
Server name: 8c30db968198
Server name: 8dbb74943174
Server name: 8c30db968198
Server name: 8dbb74943174
Server name: 8c30db968198
----

=== Least Connections 

[source, bash]
.*1. Configuration*
----
upstream backend_methods_least_conn {
    zone   backend_methods 64k;
    least_conn;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
}
----

* link:gw-methods.d/least_conn.conf[least_conn.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9022/foo | grep name ; done
Server name: 8c30db968198
Server name: 8dbb74943174
Server name: 8c30db968198
Server name: 8dbb74943174
Server name: 8c30db968198
----

=== IP Hash 

[source, bash]
.*1. Configuration*
----
upstream backend_methods_ip_hash {
    zone   backend_methods 64k;
    ip_hash;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
}
----

* link:gw-methods.d/ip_hash.conf[ip_hash.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9023/foo | grep name ; done
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8c30db968198
----

=== Hash

[source, bash]
.*1. Configuration*
----
upstream backend_methods_hash {
    zone   backend_methods 64k;
    hash $request_uri consistent;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
}
----

* link:gw-methods.d/hash.conf[hash.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9024/foo | grep name ; done
Server name: 8dbb74943174
Server name: 8dbb74943174
Server name: 8dbb74943174
Server name: 8dbb74943174
Server name: 8dbb74943174
----

=== Least Time  

[source, bash]
.*1. Configuration*
----
upstream backend_methods_least_time {
    zone   backend_methods 64k;
    least_time header;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
}
----

* link:gw-methods.d/least_time.conf[least_time.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9025/foo | grep name ; done
Server name: 8c30db968198
Server name: 8dbb74943174
Server name: 8c30db968198
Server name: 8dbb74943174
Server name: 8c30db968198
----

=== Random 

[source, bash]
.*1. Configuration*
----
upstream backend_methods_random {
    zone   backend_methods 64k;
    random two least_time=last_byte;
    server 10.1.20.203:8080;
    server 10.1.20.204:8080;
}
----

* link:gw-methods.d/random.conf[random.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9026/foo | grep name ; done
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8dbb74943174
Server name: 8dbb74943174
Server name: 8c30db968198
----

=== Server Weights

[source, bash]
.*1. Configuration*
----
upstream backend_methods_weight {
    zone   backend_methods 64k;
    server 10.1.20.203:8080 weight=5;
    server 10.1.20.204:8080 weight=1;
}
----

* link:gw-methods.d/weight.conf[weight.conf]

[source, bash]
.*2. Test*
----
$ for i in {1..5} ; do curl -s http://10.1.10.195:9027/foo | grep name ; done
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8c30db968198
Server name: 8dbb74943174
----

== Source IP Preserve

=== X-Forwarded-For

[source, bash]
.*1. Configuration*
----
  location / {
    status_zone location_backendXFF;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://backendXFF;
  }
----

* link:gw-preserve.d/xff.conf[xff.conf]

[source, bash]
.*2. Test*
----
$ curl http://10.1.10.195:9031/foo
Server address: 172.17.0.2:8080
Server name: 8c30db968198
Date: 20/Apr/2023:11:57:17 +0000
URI: /foo
Request ID: 283cb3a13e190ed8f4433867df6db416
----

== API Gateway

=== Content Caching

link:cache.adoc[Content Caching]
