apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: bot-sigs
  namespace: filter-by-content
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Brute Force Attack
    description: Medium accuracy user defined signature with tag
    name: Bot_medium_acc
    risk: medium
    rule: content:"test123"; nocase;
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: filter-content
