FROM cloudadc/nginx-alpine:0.1

COPY conf/dev/api.conf /etc/nginx/conf.d/
COPY conf/dev/keyvals.conf /etc/nginx/conf.d/
COPY conf/dev/ssl.conf /etc/nginx/conf.d/

COPY conf/dev/crt/example.com.crt /etc/nginx
COPY conf/dev/crt/example.com.key /etc/nginx
COPY conf/dev/crt/example.com.pass /etc/nginx

EXPOSE 8001-8020
EXPOSE 8443

STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]
