= Nginx DevOps Demo
:toc: manual

== Build & Run

[source, bash]
.*Build*
----
docker build -t nginx-devops-demo .
docker tag nginx-devops-demo:latest cloudadc/nginx-devops-demo:1.0.6
docker push cloudadc/nginx-devops-demo:1.0.6
----

[source, bash]
.*Run*
----
docker run -it --rm --name backend-1 cloudadc/backend:0.1.3
docker run -it --rm --name backend-2 cloudadc/backend:0.1.3
docker run -it --rm --name test --link backend-1 --link backend-2 -p 8001-8020:8001-8020 cloudadc/nginx-devops-demo:1.0.6
----

== Parametes

[source, bash]
.*HTTP Request Headers*
----
$ curl http://127.0.0.1:8006/webroot/httpHeaders

            request: GET /webroot/httpHeaders HTTP/1.1

        client addr: 172.17.0.1:58450
        server addr: 172.17.0.3:8006

             cookie: 
                xff: 
         user agent: curl/7.64.1
----

[source, bash]
.*Upstream Server & Upstream Server Port*
----
$ curl http://127.0.0.1:8006/webroot/decision/login -v
...
< backend: 172.17.0.2:8080
< backport: 8080
----

NOTE: The Nginx default not define the parameters for Upstream Server Port, the Map are used to extract upstream server port, If upstream has multiple server, each with differrent port, this settings are much useful.

[source, bash]
.*request_time & upstream_response_time*
----
// Run request 3 times
$ for i in {1..3} ; do curl http://localhost:8006/webroot/content; echo; done
<h1> Content Page.. !</h1>
<h1> Content Page.. !</h1>
<h1> Content Page.. !</h1>

// Check access log
172.17.0.1 - 172.17.0.2:8080 -  - [25/Aug/2022:03:11:55 +0000] "GET /webroot/content HTTP/1.1" 200 26 "-" "curl/7.64.1" - 10.004 10.004
172.17.0.1 - 172.17.0.2:8080 -  - [25/Aug/2022:03:12:05 +0000] "GET /webroot/content HTTP/1.1" 200 26 "-" "curl/7.64.1" - 9.984 10.007
172.17.0.1 - 172.17.0.2:8080 -  - [25/Aug/2022:03:12:15 +0000] "GET /webroot/content HTTP/1.1" 200 26 "-" "curl/7.64.1" - 10.006 10.006
----

NOTE: `request_time` represents the request processing time in seconds with a milliseconds resolution; time elapsed between the first bytes were read from the client and the log write after the last bytes were sent to the client. `upstream_response_time` keeps time spent on receiving the response from the upstream server; the time is kept in seconds with millisecond resolution. Times of several responses are separated by commas and colons like addresses in the $upstream_addr variable. More details refer to http://nginx.org/en/docs/http/ngx_http_log_module.html and http://nginx.org/en/docs/http/ngx_http_upstream_module.html.

== proxy_redirect

[source, bash]
----
$ curl --resolve example.com:8007:127.0.0.1 http://example.com:8007/finebi -L
<h1>BI Login Page.. !</h1>
$ curl --resolve example.com:8007:127.0.0.1 http://example.com:8007/finerpt -L
<h1>BI Login Page.. !</h1>
----

NOTE: Sets the text that should be changed in the “Location” and “Refresh” header fields of a proxied server response. https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect.

== Regular Expression

[source, bash]
.*Regular Expression Syntax*
----
http://localhost:8008/regexp
----

[source, bash]
.*TEST*
----
./regexpTest.sh
----

== HTTP Basic Authentication

[source, bash]
----
$ for i in admin:admin kylin:default ; do curl -u "$i" http://localhost:8009/sec/base_auth ; done
Authentication Success,    Request Headers: authorization: [Basic YWRtaW46YWRtaW4=] host: [secBackend] connection: [close] user-agent: [curl/7.64.1] accept: [*/*] 
Authentication Success,    Request Headers: authorization: [Basic a3lsaW46ZGVmYXVsdA==] host: [secBackend] connection: [close] user-agent: [curl/7.64.1] accept: [*/*] 
----


