= Nginx DevOps Demo
:toc: manual

== Build & Run

[source, bash]
.*Build*
----
docker build -t nginx-demo .
----

[source, bash]
.*Tag*
----
docker tag nginx-demo:latest cloudadc/nginx-demo:1.0.3
----

[source, bash]
.*Start*
----
docker run -itd --rm --name test -p 8008:8008 cloudadc/nginx-demo:1.0.3
----

[source, bash]
.*Test*
----
localhost:8008/help
----

== request_time & upstream_response_time

* http://nginx.org/en/docs/http/ngx_http_log_module.html
* http://nginx.org/en/docs/http/ngx_http_upstream_module.html

* request_time - request processing time in seconds with a milliseconds resolution; time elapsed between the first bytes were read from the client and the log write after the last bytes were sent to the client.
* upstream_response_time - keeps time spent on receiving the response from the upstream server; the time is kept in seconds with millisecond resolution. Times of several responses are separated by commas and colons like addresses in the $upstream_addr variable.

* Example - link:times/times.conf[times.conf]

== Nginx Regular Expression

[source, bash]
.*Regular Expression Syntax*
----
http://localhost:8008/regexp
----

=== location /regexpNone

[source, bash]
.*TEST*
----
http://localhost:8008/regexpNone
http://localhost:8008/regexpNonehello
http://localhost:8008/regexpNone/hello
----

=== location /regexpNone/web

[source, bash]
.*TEST*
----
http://localhost:8008/regexpNone/web
http://localhost:8008/regexpNone/webhello
http://localhost:8008/regexpNone/web/hello
----

=== location ^~ /regexpRxp

[source, bash]
.*TEST*
----
http://localhost:8008/regexpRxp
http://localhost:8008/regexpRxphello
http://localhost:8008/regexpRxp/hello
----

=== location ^~ /regexpRxp/web

[source, bash]
.*TEST*
----
http://localhost:8008/regexpRxp/web
http://localhost:8008/regexpRxp/webhello
http://localhost:8008/regexpRxp/web/hello
----

=== location = /regexpEq

[source, bash]
.*TEST*
----
$ http://localhost:8008/regexpEq
----

=== location ~* /regexpInsensitive

[source, bash]
.*TEST*
----
http://localhost:8008/regexpInsensitive
http://localhost:8008/reGExpInsenSItiVe
http://localhost:8008/reGExpInsenSItiVe/hEllo
----

=== location ~* /regexpLocationBlock

[source, bash]
.*TEST*
----
http://localhost:8008/regexpLocationBlock
----

=== location ~* \.(gif|jpe?g|png|css|js|ico)$ 

[source, bash]
.*TEST*
----
http://localhost:8008/helloworld.gif
http://localhost:8008/hello/world.gif
http://localhost:8008/hello/world/test.gif
http://localhost:8008/hello/wold/test.jpg
http://localhost:8008/hello/wold/test.jpeg
http://localhost:8008/hello/wold/test.png
http://localhost:8008/hello/wold/test.css
http://localhost:8008/hello/wold/test.js
http://localhost:8008/hello/wold/test.ico
----

=== location ~ ^(/site/[0-8a-x]+/index.php)$ 

[source, bash]
.*TEST*
----
http://localhost:8008/site/012345678abcefghigklmnopqrstuvwx/index.php
http://localhost:8008/site/abcefghigklmnopqrstuvwx012345678/index.php
http://localhost:8008/site/test01/index.php
http://localhost:8008/site/01test/index.php
http://localhost:8008/site/x/index.php
----

=== location ~* "/docs/[0-8a-x]{3}/index.html"

[source, bash]
.*TEST*
----
http://localhost:8008/docs/123/index.html
http://localhost:8008/docs/abc/index.html
http://localhost:8008/docs/ax8/index.html
http://localhost:8008/docs/ax8/index.html?name=yes
----

=== location ~* "/edu/[0-8a-x]{2,4}/index.html"

[source, bash]
.*TEST*
----
http://localhost:8008/edu/aa/index.html
http://localhost:8008/edu/aaa/index.html
http://localhost:8008/edu/aaaa/index.html
http://localhost:8008/edu/a8/index.html
http://localhost:8008/edu/ax8/index.html
http://localhost:8008/edu/ax08/index.html
http://localhost:8008/edu/ax08/index.html?name=yes
----

=== location ~* ^(/foo/.*)$

[source, bash]
.*TEST*
----
http://localhost:8008/foo/
http://localhost:8008/foo/a
http://localhost:8008/foo/1
http://localhost:8008/foo/abcf
http://localhost:8008/foo/abcf/test
----

=== location ~* ^(/bar/.+)$

[source, bash]
.*TEST*
----
http://localhost:8008/bar/a
http://localhost:8008/bar/1
http://localhost:8008/bar/abcf
http://localhost:8008/bar/abcf/test
----

=== location ~* ^(/zoo/*)$

[source, bash]
.*TEST*
----
http://localhost:8008/zoo
http://localhost:8008/zoo/
----

=== location ~* ^(/moo/+)$

[source, bash]
.*TEST*
----
http://localhost:8008/moo/
----
