= Nginx Lua Module
:toc: manual

== What's this?

This page contains steps to set up nginx lua cia compiling source code.

== Compiling and Installing from Source

[source, bash]
.*Development tools Installation*
----
yum groupinstall "Development tools" -y
----

=== NGINX Only

[source, bash]
.*1. Download Source*
----
wget https://nginx.org/download/nginx-1.23.2.tar.gz
tar –zxf nginx-1.23.2.tar.gz
----

[source, bash]
.*2. Install Dependencies*
----
yum install pcre-devel –y
yum install zlib-devel –y
yum install openssl-devel -y
----

[source, bash]
.*3. Compiling Source*
----
cd nginx-1.23.2 && ./configure --sbin-path=/usr/local/nginx/nginx --conf-path=/usr/local/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-http_ssl_module --with-stream
make && make install
----

[source, bash]
.*4. Starting & Testing*
----
cd /usr/local/nginx && ./nginx 

curl http://localhost:80 -I
HTTP/1.1 200 OK
Server: nginx/1.23.2
Date: Mon, 21 Nov 2022 11:25:26 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Mon, 21 Nov 2022 11:22:16 GMT
Connection: keep-alive
ETag: "637b5f68-267"
Accept-Ranges: bytes
----

=== NGINX + PCRE/zlib/openssl

[source, bash]
.*1. Download Source*
----
wget https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz
wget http://zlib.net/zlib-1.2.13.tar.gz
wget https://www.openssl.org/source/openssl-1.1.1s.tar.gz
wget https://nginx.org/download/nginx-1.23.2.tar.gz
for i in $(ls *.tar.gz) ; do tar -zxf $i ; done
----

[source, bash]
.*2. Compiling Source*
----
cd nginx-1.23.2 && ./configure --sbin-path=/usr/local/nginx/nginx --conf-path=/usr/local/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-openssl=/root/src/openssl-1.1.1s --with-pcre=/root/src/pcre-8.45 --with-zlib=/root/src/zlib-1.2.13 --with-http_ssl_module --with-stream
make
make install
----

[source, bash]
.*3. Starting & Testing*
----
cd /usr/local/nginx && ./nginx 

$ curl http://localhost:80 -I
HTTP/1.1 200 OK
Server: nginx/1.23.2
Date: Mon, 21 Nov 2022 07:36:12 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Mon, 21 Nov 2022 07:32:34 GMT
Connection: keep-alive
ETag: "637b2992-267"
Accept-Ranges: bytes
----

=== NGINX + PCRE/zlib/openssl/Lua

[source, bash]
.*1. Install Dependencies*
----
yum install pcre-devel -y
----

[source, bash]
.*2. Download Source*
----
wget http://zlib.net/zlib-1.2.13.tar.gz
wget https://www.openssl.org/source/openssl-1.1.1s.tar.gz
wget https://nginx.org/download/nginx-1.23.2.tar.gz
for i in $(ls *.tar.gz) ; do tar -zxf $i ; done
----

[source, bash]
.*3. Prepare Dynamic Module*
----
git clone https://github.com/openresty/lua-nginx-module.git
git clone https://github.com/vision5/ngx_devel_kit.git
----

[source, bash]
.*4. Prepare LuaJIT EVN*
----
wget  https://github.com/openresty/luajit2/archive/refs/tags/v2.1-20201012.tar.gz
tar -xvf v2.1-20201012.tar.gz 
cd luajit2-2.1-20201012/ 
make 
make install
export LUAJIT_LIB=/usr/local/lib 
export LUAJIT_INC=/usr/local/include/luajit-2.1
----

[source, bash]
.*5. Compiling Source*
----
cd nginx-1.23.2 && ./configure --sbin-path=/usr/local/nginx/nginx --conf-path=/usr/local/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-openssl=/root/src/openssl-1.1.1s --with-zlib=/root/src/zlib-1.2.13 --with-pcre --with-http_ssl_module --with-stream --add-dynamic-module=/root/src/ngx_devel_kit --add-dynamic-module=/root/src/lua-nginx-module
make
make install
----

[source, bash]
.*6. Verifying Install*
----
$ ls -l /usr/local/nginx/nginx
-rwxr-xr-x 1 root root 8472744 Nov 21 16:11 /usr/local/nginx/nginx

$ ls -l /usr/local/nginx/modules/
total 2640
-rwxr-xr-x 1 root root   82032 Nov 21 16:11 ndk_http_module.so
-rwxr-xr-x 1 root root 2614304 Nov 21 16:11 ngx_http_lua_module.so
----

[source, bash]
.*7. Starting & Testing*
----
cd /usr/local/nginx && ./nginx

$ curl http://localhost:80 -I
HTTP/1.1 200 OK
Server: nginx/1.23.2
Date: Mon, 21 Nov 2022 08:13:31 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Mon, 21 Nov 2022 08:11:01 GMT
Connection: keep-alive
ETag: "637b3295-267"
Accept-Ranges: bytes
----

==== Lua HelloWorld Example

[source, bash]
.*1. Prepare lua-resty-core and lua-resty-lrucache*
----
wget https://github.com/openresty/lua-resty-core/archive/refs/tags/v0.1.24.tar.gz
wget https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v0.13.tar.gz
tar -xvf v0.1.24.tar.gz
tar -xvf v0.13.tar.gz

cd lua-resty-core-0.1.24/ && make install PREFIX=/opt/nginx

cd ../lua-resty-lrucache-0.13/ && make install PREFIX=/opt/nginx
----

[source, bash]
.*2. modify nginx.conf, in the `main` contain add dynamic modules*
----
load_module modules/ndk_http_module.so;
load_module modules/ngx_http_lua_module.so;
----

[source, bash]
.*3. add necessary `lua_package_path` directive to `nginx.conf`, in the http context*
----
lua_package_path "/opt/nginx/lib/lua/?.lua;;";
----

[source, bash]
.*4. Create manually link lib*
----
touch /etc/ld.so.conf.d/luajit.conf
echo "/usr/local/lib" >> /etc/ld.so.conf.d/luajit.conf
ldconfig
----

[source, bash]
.*5. Create Hello Lua*
----
mkdir /usr/local/nginx/lua

cat >> /usr/local/nginx/lua/hello_lua.lua << EOF
ngx.say("hello lua, by NGINX");
EOF

chmod a+x /usr/local/nginx/lua/hello_lua.lua 
----

[source, bash]
.*6. Add lua location*
----
location /lua {    
    default_type 'text/html';    
    content_by_lua_file lua/hello_lua.lua; 
}
----

[source, bash]
.*7. Start NGINX*
----
cd /usr/local/nginx && ./nginx 
----

[source, bash]
.*8. Testing*
----
$ curl http://localhost:80/lua
hello lua, by NGINX

$ curl http://localhost:80/lua -I
HTTP/1.1 200 OK
Server: nginx/1.23.2
Date: Mon, 21 Nov 2022 08:59:54 GMT
Content-Type: text/html
Connection: keep-alive
----
