apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: illegal-file-type-sigs
  namespace: illegal-file-type
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Other Application Activity
    description: Medium accuracy user defined signature with tag
    name: Illegal File Type
    risk: medium
    rule: "re2:\"/\\.(php|asp|aspx)$/U\"; nocase; objonly;"
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: illegal-file-type
