apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: dataguard-alarm
  namespace: rs2-example
spec:
  policy:
    signature-requirements:
    - tag: rs2-example
    signature-sets: 
    - name: rs2-example
      block: true
      signatureSet: 
        filter:
          tagValue: rs2-example
          tagFilter: eq
    applicationLanguage: utf-8
    blocking-settings:
      violations:
      - alarm: true
        block: false
        name: VIOL_DATA_GUARD
    enforcementMode: blocking
    name: dataguard-alarm
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
