apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: application-admin-access-sigs
  namespace: application-admin-access
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Other Application Activity
    description: Medium accuracy user defined signature with tag
    name: Illegal File Type
    risk: medium
    rule: "re2:\"/\\/redis-admin\\/|\\/axis2-web\\/|\\/axis2-admin\\/|\\/manager\\/html|\\/host-manager\\/html|\\/console\\/j_security_check|\\/ibm\\/console|\\/wp-content\\/|\\/wp-admin\\/|\\/wp-conf\\//U\"; nocase; objonly;"
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: application-admin-access
