apiVersion: v1
kind: Namespace
metadata:
  name: host-validation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-svc-1-app
  name: app-svc-1-app
  namespace: host-validation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-svc-1-app
  template:
    metadata:
      labels:
        app: app-svc-1-app
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-svc-1-app
  name: app-svc-1
  namespace: host-validation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-svc-1-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-svc-2-app
  name: app-svc-2-app
  namespace: host-validation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-svc-2-app
  template:
    metadata:
      labels:
        app: app-svc-2-app
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-svc-2-app
  name: app-svc-2
  namespace: host-validation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-svc-2-app
  type: NodePort
