apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: illegal-directory-access-sigs
  namespace: illegal-directory-access
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Abuse of Functionality
    description: Medium accuracy user defined signature with tag
    name: Illegal Directory Access
    risk: medium
    rule: "re2:\"/\\/images\\/|\\/media\\/|\\/uploads\\/|\\/pic\\/|\\/img\\/|\\/tmp\\/|\\/pictures\\//U\"; nocase; objonly; re2:\"/\\.(php|asp|aspx|jsp|jspx)$/U\"; nocase; objonly;"
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: illegal-directory-access
