= Nginx Dump Plane
:toc: manual

== What's dumpplane?

The `dumpplane` is a tool work with link:https://github.com/nginxinc/crossplane[crossplane] to dump `nginx -T` results to MongoDB.

The `nginx -T` output should same to a file and copy to a directory, which used as input of `dumpplane` tool.

[source, bash]
----
usage: dumpplane <commands> [options] [input]

commands:
  parse                 parse a nginx dump(nginx -T) file to raw object

  dump                  dump nginx crossplane result to mongodb

options:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit
  --output              set dumpplane output file path. default data
  --cpout               set crossplane(https://github.com/nginxinc/crossplane) parse output file path. default same as dumpplane output
                            suggest crossplane commands is for i in $(ls data/) ; do crossplane parse -o data/$i.json data/$i/nginx.conf; done 
  --uri                 mongodb connection string, default mongodb://127.0.0.1:27017, refer to https://www.mongodb.com/docs/manual/reference/connection-string/ for details

input:
                        set nginx -T dump file directory, input is mandatory

----

== Prerequisites for run dumpplane

=== MongoDB

This section including steps to setup MongoDB on local machine.

[source, bash]
.*1. Cfreate DBpath*
----
mkdir nginx
----

[source, bash]
.*2. Start a single node mongodb*
----
mongod --dbpath nginx/
----

[source, bash]
.*3. connect to mongoDB via mongo shell*
----
$ mongosh 
Current Mongosh Log ID:	6455bd1f1642278a956b6a76
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.1
Using MongoDB:		6.0.3
Using Mongosh:		1.6.1
----

[source, bash]
.*4. Create db and collection*
----
use nginx
----

=== Java

[source, bash]
.*Java Runtime time V11 or above version*
----
$ java --version
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
----

=== crossplane

[source, bash]
.*link:https://github.com/nginxinc/crossplane[crossplane] 0.5.8 and above version*
----
$ crossplane --version
crossplane 0.5.8
----

== How to run?

In order to run `dumpplane`, you need make sure all link:#prerequisites-for-run-dumpplane[prerequisites for run dumpplane] are satisfied.

Refer blow steps to run `dumpplane`.

=== Step 1: prepare nginx dump file

[source, bash]
----
$ ls input/
nginx.conf_10.1.10.171	nginx.conf_10.1.10.195	nginx.conf_15.55.240.8
----

NOTE: `input` is folder, which contains 3 files, each file are output of `nginx -T`.

=== Step 2: dumpplane parse

[source, bash]
----
$ dumpplane parse input

split nginx.conf_10.1.10.171 to data/nginx.conf_10.1.10.171, total blocks: 6
split nginx.conf_15.55.240.8 to data/nginx.conf_15.55.240.8, total blocks: 8
split nginx.conf_10.1.10.195 to data/nginx.conf_10.1.10.195, total blocks: 58
----

=== Step 3: crossplane parse

[source, bash]
----
for i in $(ls data/) ; do crossplane parse -o data/$i.json data/$i/nginx.conf; done 
----

NOTE: The *data* is dumpplane output file path, recommended crossplane output file are same as dumpplane output file path, or else you need specify `--cpout` while running dumpplane dump.

NOTE: Current crossplane parse output must equals `nginx -T` plus `.json`.

=== Step 4: dumpplane dump

[source, bash]
----
$ dumpplane dump input

write nginx.conf_10.1.10.171 to DB was acknowledged, matched count: 0
write nginx.conf_15.55.240.8 to DB was acknowledged, matched count: 0
write nginx.conf_10.1.10.195 to DB was acknowledged, matched count: 0
----

This step will dump both `dumpplane` parsed result and `crossplane` parsed result as a single document to MongoDB.

NOTE: `nginx -T` output file name used as a primary key, which means if same file be dumped many times, only the 1st time is insert, the rest are upset.

=== Step 5: nginx management & governance

Refer to below sections for details.

== NGINX Management & Governance


