apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: xff-injection-sigs
  namespace: demo-bar
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Brute Force Attack
    description: Medium accuracy user defined signature with tag
    name: XFF Injection
    risk: medium
    rule: "re2:\"/X-Forwarded-For:.*?\\s+(select|update|union|wait|sleep|insert|chr|char|substr|substring)/\"; nocase;"
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: xff-injection
