apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: illegal-file-extension-sigs
  namespace: demo-foo
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Other Application Activity
    description: Medium accuracy user defined signature with tag
    name: Illegal File Extension
    risk: medium
    rule: "re2:\"/(\\.pkcs12|\\.svn|\\.htaccess|\\.old|\\.sql|\\.bak|\\.tar|\\.pem|\\.pwd|\\.mdb|\\.der|\\.swp|\\.env|\\.yml|\\.db|\\.class|\\.dmp|\\.war|\\.idea|\\.log|\\.gz|\\.git|\\.vimrc|\\.sh|\\.DS_Store|\\.history|\\.project|\\.cgi|\\.conf|\\.pfx|\\.p12|\\.bash_history|\\.swo|\\.pl|\\.core|\\.pyc|\\.raw|\\.viminfo|\\.bp|\\.save|robots.txt)$/U\"; nocase; objonly;"
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: illegal-file-extension
